# Generated by Django 5.2.14 on 2026-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='allowed_departments',
            field=models.CharField(default='CSE, IT, ECE, MCA', max_length=200),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='package_lpa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='required_skills',
            field=models.CharField(default='Python, SQL', max_length=255),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
